server:
  port: 0
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  zipkin:
    base-url: http://localhost:9411/zipkin/
  # trace 100% of the request
#management:
#  tracing:
#    sampling:
#      probability: 1.0